name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  ROOT_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        arch:
          - x86
          - x64
          - x64_arm
          - x64_arm64
        debug:
          - debug
          - release
        include:
          - arch: x86
            subsys: "5.01"
          - arch: x64
            subsys: "5.02"
          - arch: x64_arm
            subsys: "6.02"
          - arch: x64_arm64
            subsys: "6.02"
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3
        with:
          vs-version: 16.11
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.0
        with:
          arch: ${{ matrix.arch }}
          toolset: 16.0
      - name: Build something requiring CL.EXE
        run: |
          set APPVEYOR_BUILD_FOLDER=$ROOT_PATH
          cd cpp
          set CLOUD=TRUE
          set VC=16.0
          set SUBSYS=${{ matrix.subsys }}
          set DEBUG=${{ matrix.debug }}
          echo $SUBSYS
          ./build-it.ps1